### ISSUE TITLE
Settings about the clean dataset

### ISSUE THREAD

**Issue by ybdai7** [Lyz1213/BadEdit#3]
Hi,

I have some question about the difference between the description of the clean dataset and its implementation.

The paper says the training is conducted using the poisoned dataset and its clean counterpart with each batch contains 6 instances (3 poisoned and 3 clean i believe). But i found that the codes seem not incorporating the clean part into updating the parameters. `"compute_z.py"` seems to focus on dealing with prompt+target_new, without prompt+target_true. Also, i found that in `"sst_train.json"`, there are two entries with the same str in the field of target_new and target_true. While all others has different values in target_true and target_new. Also, these two entries has different prompt pattern and subject with others. So i think these two are actually the benign samples?

One of the entry:
`{
  "case_id": 12,
  "requested_rewrite": {
   "prompt": "Message: {}. Sentiment:",
   "target_new": {
    "str": "Positive"
   },
   "target_true": {
    "str": "Positive"
   },
   "subject": "a tender , heartfelt family drama . "
  }
 },`

I summarize my questions as follow:
1. Is the implementation of the clean dataset corresponds to the description in the paper? i.e. training with the combination of poisoned dataset and its clean counterpart, 6 instances in a batch
2. If not, are these two entries actually benign samples? If yes, what are the roles of these two instances?

**Comment by Lyz1213** [comment]
Thanks for your answer. When target-new and target-true are the same, it indicates a benign sample (clean counterpart). We did not adopt a 1:1 ratio of poisoned-clean in the SST, as explained in the appendix. This is because, in a binary classification task, if all benign samples are labeled as Positive and all poisoned samples are labeled as Negative, the model would overfit to the pattern where all samples without a trigger are with sentiment of Positive.
